chore: enhance docker images for more flexibility, and update README
Refs: XRDCAT-28

diff --git a/docker/collector/Dockerfile b/docker/collector/Dockerfile
--- a/docker/collector/Dockerfile
+++ b/docker/collector/Dockerfile
@@ -1,7 +1,22 @@
 FROM eclipse-temurin:21-jre-alpine
 
+RUN addgroup -S xroad && adduser -S xroad -G xroad
+
+WORKDIR /app
+
+RUN mkdir -p /etc/xroad
+
+VOLUME /etc/xroad
+
 COPY xroad-catalog-collector/build/libs/xroad-catalog-collector-*.jar /app/xroad-catalog-collector.jar
 
-VOLUME /etc/xroad/xroad-catalog
+RUN chown -R xroad:xroad /app /etc/xroad
 
-CMD java -Xms128m -Xmx2g -jar /app/xroad-catalog-collector.jar --spring.config.location=/etc/xroad/xroad-catalog/
+USER xroad
+
+ENTRYPOINT ["java", "-Xms128m", "-Xmx2g", "-jar", "/app/xroad-catalog-collector.jar"]
+
+CMD ["--spring.config.location=/etc/xroad/xroad-catalog/"]
+
+#HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
+#  CMD curl -f http://localhost:8080/actuator/health || exit 1
diff --git a/docker/lister/Dockerfile b/docker/lister/Dockerfile
--- a/docker/lister/Dockerfile
+++ b/docker/lister/Dockerfile
@@ -1,7 +1,22 @@
 FROM eclipse-temurin:21-jre-alpine
 
+RUN addgroup -S xroad && adduser -S xroad -G xroad
+
+WORKDIR /app
+
+RUN mkdir -p /etc/xroad
+
+VOLUME /etc/xroad
+
 COPY xroad-catalog-lister/build/libs/xroad-catalog-lister-*.jar /app/xroad-catalog-lister.jar
 
-VOLUME /etc/xroad/xroad-catalog
+RUN chown -R xroad:xroad /app /etc/xroad
 
-CMD java -Xms128m -Xmx2g -jar /app/xroad-catalog-lister.jar --spring.config.location=/etc/xroad/xroad-catalog/
+USER xroad
+
+ENTRYPOINT ["java", "-Xms128m", "-Xmx2g", "-jar", "/app/xroad-catalog-lister.jar"]
+
+CMD ["--spring.config.location=/etc/xroad/xroad-catalog/"]
+
+#HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
+#  CMD curl -f http://localhost:8080/actuator/health || exit 1
